on:
  workflow_dispatch: # Manual dispatch event
  schedule:
    - cron: '0 10 * * *'

permissions:
  id-token: write # This is required for requesting the JWT (JSON Web Token)
  contents: read  # This is required for actions/checkout

jobs:
  AWS-Step-Functions-Cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Installing AWS Step Functions Module
        shell: pwsh
        run: |
          Install-Module -Name AWS.Tools.StepFunctions -Scope CurrentUser -Force
          
      - name: Authenticate to AWS using OpenID Connect
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::295793222430:role/github-actions-cleanup
          aws-region: us-east-1

      - name: Clone Source Code from My GitHub Repository to run powershell script
        uses: actions/checkout@v4.1.7
      
      - name: Cleanup AWS Step Functions Resources
        shell: pwsh
        run: |
          ./aws-cleanup-for-all-resources.ps1

  AWS-EC2-Activity-Cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Installing AWS EC2 Module
        shell: pwsh
        run: |
          Install-Module -Name AWS.Tools.EC2 -Scope CurrentUser -Force
          
      - name: Authenticate to AWS using OpenID Connect
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::295793222430:role/github-actions-cleanup
          aws-region: us-east-1

      - name: Clone Source Code from My GitHub Repository to run powershell script
        uses: actions/checkout@v4.1.7
      
      - name: Cleanup AWS EC2 Resources
        shell: pwsh
        run: |
          ./aws-cleanup-for-all-resources.ps1
